/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CrearCuenta;

import java.awt.Color;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import login_trabajo.ConexionMYSQL;
import login_trabajo.Login;

/**
 *
 * @author Gabo
 */
public class CrearCuenta1 extends javax.swing.JFrame {

    /**
     * Creates new form CrearCuenta1
     */
    public CrearCuenta1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg3 = new javax.swing.JPanel();
        bg4 = new javax.swing.JPanel();
        TxtNombre = new javax.swing.JTextField();
        TxtContraseña = new javax.swing.JPasswordField();
        Nombre = new javax.swing.JLabel();
        Contraseña = new javax.swing.JLabel();
        SeparadorNombre = new javax.swing.JSeparator();
        SeparadorContraseña = new javax.swing.JSeparator();
        BotonCrearCuenta = new javax.swing.JToggleButton();
        CorreoElectronicoLabel = new javax.swing.JLabel();
        TxtMail = new javax.swing.JTextField();
        SeparadorContraseña1 = new javax.swing.JSeparator();
        Contraseña1 = new javax.swing.JLabel();
        TxtContraseñaCon = new javax.swing.JPasswordField();
        SeparadorContraseña2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg3.setBackground(new java.awt.Color(164, 252, 165));

        bg4.setBackground(new java.awt.Color(224, 252, 164));

        TxtNombre.setBackground(new java.awt.Color(224, 252, 164));
        TxtNombre.setText("Escriba su nombre usuario");
        TxtNombre.setBorder(null);
        TxtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TxtNombreMousePressed(evt);
            }
        });
        TxtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombreActionPerformed(evt);
            }
        });

        TxtContraseña.setBackground(new java.awt.Color(224, 252, 164));
        TxtContraseña.setText("jPasswordField1");
        TxtContraseña.setBorder(null);
        TxtContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TxtContraseñaMousePressed(evt);
            }
        });
        TxtContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtContraseñaActionPerformed(evt);
            }
        });

        Nombre.setBackground(new java.awt.Color(224, 252, 164));
        Nombre.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        Nombre.setForeground(new java.awt.Color(0, 0, 0));
        Nombre.setText("NOMBRE ");

        Contraseña.setBackground(new java.awt.Color(224, 252, 164));
        Contraseña.setForeground(new java.awt.Color(0, 0, 0));
        Contraseña.setText("CONTRASEÑA");

        BotonCrearCuenta.setText("Crear Cuenta");
        BotonCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCrearCuentaActionPerformed(evt);
            }
        });

        CorreoElectronicoLabel.setBackground(new java.awt.Color(224, 252, 164));
        CorreoElectronicoLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        CorreoElectronicoLabel.setForeground(new java.awt.Color(0, 0, 0));
        CorreoElectronicoLabel.setText("CORREO ELECTRONICO");

        TxtMail.setBackground(new java.awt.Color(224, 252, 164));
        TxtMail.setText("Ingrese correo electronico");
        TxtMail.setBorder(null);
        TxtMail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TxtMailMousePressed(evt);
            }
        });
        TxtMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtMailActionPerformed(evt);
            }
        });

        Contraseña1.setBackground(new java.awt.Color(224, 252, 164));
        Contraseña1.setForeground(new java.awt.Color(0, 0, 0));
        Contraseña1.setText("INGRESE DE NUEVO SU CONTRASEÑA");

        TxtContraseñaCon.setBackground(new java.awt.Color(224, 252, 164));
        TxtContraseñaCon.setText("jPasswordField1");
        TxtContraseñaCon.setBorder(null);
        TxtContraseñaCon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TxtContraseñaConMousePressed(evt);
            }
        });
        TxtContraseñaCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtContraseñaConActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bg4Layout = new javax.swing.GroupLayout(bg4);
        bg4.setLayout(bg4Layout);
        bg4Layout.setHorizontalGroup(
            bg4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(bg4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtContraseñaCon)
                    .addGroup(bg4Layout.createSequentialGroup()
                        .addComponent(TxtNombre)
                        .addContainerGap())
                    .addGroup(bg4Layout.createSequentialGroup()
                        .addGroup(bg4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bg4Layout.createSequentialGroup()
                                .addComponent(Contraseña)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(TxtContraseña))
                        .addGap(285, 285, 285))
                    .addGroup(bg4Layout.createSequentialGroup()
                        .addComponent(TxtMail, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(120, Short.MAX_VALUE))
                    .addGroup(bg4Layout.createSequentialGroup()
                        .addGroup(bg4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SeparadorContraseña2, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Contraseña1)
                            .addComponent(SeparadorContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SeparadorContraseña1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonCrearCuenta)
                            .addComponent(CorreoElectronicoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SeparadorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        bg4Layout.setVerticalGroup(
            bg4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg4Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SeparadorContraseña1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Contraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SeparadorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Contraseña1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtContraseñaCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SeparadorContraseña2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(CorreoElectronicoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtMail, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SeparadorContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotonCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout bg3Layout = new javax.swing.GroupLayout(bg3);
        bg3.setLayout(bg3Layout);
        bg3Layout.setHorizontalGroup(
            bg3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg3Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(bg4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );
        bg3Layout.setVerticalGroup(
            bg3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg3Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(bg4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNombreActionPerformed

    private void TxtMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtMailActionPerformed

    private void TxtNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtNombreMousePressed
        
        if (TxtNombre.getText().equals("Escriba su nombre usuario")) {
            TxtNombre.setText("");
            TxtNombre.setForeground(Color.gray);

        }
        if (String.valueOf(TxtContraseña.getPassword()).isEmpty()) {
            TxtContraseña.setText("***********");
            TxtContraseña.setForeground(Color.gray);

        }
         if (TxtMail.getText().isEmpty()) {
            TxtMail.setText("Ingrese correo electronico");
            TxtMail.setForeground(Color.gray);
            TxtNombre.setText("");
            TxtNombre.setForeground(Color.gray);
            
            
            
            
        }
    }//GEN-LAST:event_TxtNombreMousePressed

    private void TxtContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtContraseñaActionPerformed

    private void TxtContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtContraseñaMousePressed
         if (String.valueOf(TxtContraseña.getPassword()).equals("***********")) {
            TxtContraseña.setText("");
            TxtContraseña.setForeground(Color.gray);
            
        }
        if (TxtNombre.getText().isEmpty()) {
            TxtNombre.setText("Escriba su nombre usuario");
            TxtNombre.setForeground(Color.gray);
            TxtContraseña.setText("");
            TxtContraseña.setForeground(Color.gray);
            
        }
        if (TxtMail.getText().isEmpty()) {
            TxtMail.setText("Ingrese correo electronico");
            TxtMail.setForeground(Color.gray);
            TxtContraseña.setText("");
            TxtContraseña.setForeground(Color.gray);
            
            
            
            
        }
    }//GEN-LAST:event_TxtContraseñaMousePressed

    private void TxtMailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtMailMousePressed
        if (TxtMail.getText().equals("Ingrese correo electronico")) {
            TxtMail.setText("");
            TxtMail.setForeground(Color.gray);

        }
        if (String.valueOf(TxtContraseña.getPassword()).isEmpty()) {
            TxtContraseña.setText("***********");
            TxtContraseña.setForeground(Color.gray);

        }
        if (TxtNombre.getText().isEmpty()) {
            TxtNombre.setText("Escriba su nombre usuario");
            TxtNombre.setForeground(Color.gray);
            TxtContraseña.setText("");
            TxtContraseña.setForeground(Color.gray);
           
        }
        
    }//GEN-LAST:event_TxtMailMousePressed

    private void BotonCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCrearCuentaActionPerformed
       
        SqlUsuario modSql = new SqlUsuario();
        Usuario mod = new Usuario();
        
        String pass = new String(TxtContraseña.getPassword());
        String passCon = new String (TxtContraseñaCon.getPassword());
        
        if (pass.equals(passCon)) {
            
           String nuevoPass = Hash.sha1(pass);
           
           mod.setNombre(TxtNombre.getText());
           mod.setContraseña(nuevoPass);
           mod.setMail(TxtMail.getText());
           
            if (modSql.registar(mod)) {
                JOptionPane.showMessageDialog(null, "El usuario se creo correctamente");
                Login l1 =  new Login();
                l1.setVisible(true);
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(null, "El usuario no se pudo crear");
            }
            
        }
        else{
            JOptionPane.showMessageDialog(null, "Las contraseñas no coiciden");
        }
        
        
        
          
    }//GEN-LAST:event_BotonCrearCuentaActionPerformed

    private void TxtContraseñaConMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtContraseñaConMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtContraseñaConMousePressed

    private void TxtContraseñaConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtContraseñaConActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtContraseñaConActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearCuenta1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BotonCrearCuenta;
    private javax.swing.JLabel Contraseña;
    private javax.swing.JLabel Contraseña1;
    private javax.swing.JLabel CorreoElectronicoLabel;
    private javax.swing.JLabel Nombre;
    private javax.swing.JSeparator SeparadorContraseña;
    private javax.swing.JSeparator SeparadorContraseña1;
    private javax.swing.JSeparator SeparadorContraseña2;
    private javax.swing.JSeparator SeparadorNombre;
    private javax.swing.JPasswordField TxtContraseña;
    private javax.swing.JPasswordField TxtContraseñaCon;
    private javax.swing.JTextField TxtMail;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JPanel bg3;
    private javax.swing.JPanel bg4;
    // End of variables declaration//GEN-END:variables
}
